/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.DockerPushImage
import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import com.github.breadmoirai.githubreleaseplugin.GithubReleaseTask
import io.github.sgpublic.CreateTag
import io.github.sgpublic.aptInstall
import io.github.sgpublic.command

plugins {
    alias(libs.plugins.docker.api)
    alias(libs.plugins.release.github)
    alias(libs.plugins.buildsrc.utils)
}

group = "io.github.sgpublic"
version = "3.5.0"

tasks {
    val tag = "mhmzx/nas-tools"

    val createTag by creating(CreateTag::class) {
        token = findEnv("publishing.gitlab.token")
    }

    val installXunlei by creating {
        group = "nas-tools"
        doLast {
            delete(
                "./src/main/nas-tools/nas-tools/third_party_nas_xunlei",
                "./src/main/nas-tools/nas-tools/app/downloader/client",
            )
            copy {
                from("./src/main/xunlei/third_party")
                into("./src/main/nas-tools/nas-tools/third_party_nas_xunlei")
            }
            copy {
                from("./src/main/xunlei/nasxunlei.py")
                into("./src/main/nas-tools/nas-tools/app/downloader/client")
            }
        }
    }

    val genSites by creating {
        group = "nas-tools"
        doFirst {
            exec {
                workingDir(File(projectDir, "src/main/nas-tools-site"))
                commandLine("python3", "nastools_generate.py")
            }
        }
    }
    val installUserSite by creating {
        group = "nas-tools"
        dependsOn(genSites)
        doLast {
            delete("./src/main/nas-tools/nas-tools/web/backend/user.sites.bin")
            copy {
                from("./src/main/nas-tools-site/nas-tools/user.sites.bin")
                into("./src/main/nas-tools/nas-tools/web/backend")
            }
        }
    }

    val dockerCreateDockerfile by creating(Dockerfile::class) {
        dependsOn(installXunlei, installUserSite)
        doFirst {
            delete(layout.buildDirectory.file("nas-tools"))
            copy {
                from("./src/main/nas-tools")
                into(layout.buildDirectory.dir("nas-tools/rootf"))
            }
        }
        group = "docker"
        destFile = layout.buildDirectory.file("nas-tools/Dockerfile")
        from("mhmzx/poetry-runner:3.10-bullseye")
        runCommand(command(
            "apt-get update",
            aptInstall(
                "apt-transport-https",
                "apt-utils",
                "bash",
                "ca-certificates",
                "chromium",
                "chromium-driver",
                "curl",
                "dumb-init",
                "ffmpeg",
                "fuse3",
                "git",
                "inotify-tools",
                "locales",
                "musl-dev",
                "netcat",
                "procps",
                "redis",
                "sudo",
                "tzdata",
                "wget",
                "xvfb",
                "zip",
            ),
        ))
        copyFile("./rootf", "/")
    }
    val dockerBuildImage by creating(DockerBuildImage::class) {
        group = "docker"
        dependsOn(dockerCreateDockerfile)
        inputDir = layout.buildDirectory.dir("nas-tools")
        dockerFile = dockerCreateDockerfile.destFile
        images.add(provider { "$tag:v$version" })
        images.add(provider { "$tag:latest" })
        images.add("$tag:latest")
        noCache = true
    }

    val dockerPushBuildBookImageOfficial by creating(DockerPushImage::class) {
        group = "docker"
        dependsOn(dockerBuildImage)
        images.add(provider { "$tag:v$version" })
        images.add(provider { "$tag:latest" })
        images.add("$tag:latest")
    }

    val githubRelease by getting(GithubReleaseTask::class) {
        authorization = provider {
            "Token ${findEnv("publishing.github.token").get()}"
        }
        owner = "sgpublic"
        repo = "nas-tools"
        tagName = provider { "v$version" }
        releaseName = provider { "v$version" }
        overwrite = true
    }
}

fun findEnv(name: String) = provider {
    findProperty(name)?.toString()?.takeIf { it.isNotBlank() }
        ?: System.getenv(name.replace(".", "_").uppercase())
}

docker {
    registryCredentials {
        username = findEnv("publishing.docker.username")
        password = findEnv("publishing.docker.password")
    }
}
