version: '3.1'
services:
  # 仅供开发测试的 docker-compose 文件，一般用户请使用 README.md 中给出的示例！
  nas-tools:
    image: mhmzx/nas-tools:v3.5.0
    ports:
      - 3000:3000
    networks:
      - nas-network
    volumes:
      - /vol1/1000/App/nas-tools/data:/config
      - /vol2/var/cache:/.cache
      - /vol3/1000:/mnt/resource
    environment:
      PUID: 1000
      PGID: 1001

networks:
  nas-network:
    external: true
