version: '3.1'
services:
  # 仅供开发测试的 docker-compose 文件，一般用户请使用 README.md 中给出的示例！
  nas-tools:
    image: mhmzx/nas-tools:v3.5.0
    ports:
      - 3000:3000
    networks:
      - nas-toolschain-network
    volumes:
      - /mnt/core/app/nastools/config:/config
      - /mnt/onedrive/Backups/NasTools:/config/backup_file
      - /mnt/core/var/tmp/nastools:/home/poetry-runner/.cache
      - /mnt/resource:/mnt/resource
      - /mnt/pt/PT:/mnt/pt
      - /mnt/pt/Private:/mnt/private

networks:
  nas-toolschain-network:
    name: nas-toolschain-network
